runtime: python27
api_version: 1
threadsafe: true
service: ang-loop
handlers:
- url: /
  static_files: dist/stock-viewer/index.html
  upload: dist/stock-viewer/index.html
- url: /
  static_dir: dist/stock-viewer

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE